<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">hmacHash</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required algorithm</value>
    <value>[i] field:0:required inputString</value>
    <value>[i] field:0:required secretKey</value>
    <value>[o] field:0:required hashValue</value>
    <value>[o] field:0:required errorMessage</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQ0KDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5n
ZXRDdXJzb3IoKTsNCglTdHJpbmcJYWxnb3JpdGhtID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlw
ZWxpbmVDdXJzb3IsICJhbGdvcml0aG0iICk7DQoJU3RyaW5nCWlucHV0U3RyaW5nID0gSURhdGFV
dGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJpbnB1dFN0cmluZyIgKTsNCglTdHJpbmcJ
c2VjcmV0S2V5ID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzZWNyZXRL
ZXkiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNClN0cmluZyBoYXNoVmFsdWU9IG51
bGw7DQpTdHJpbmcgZXJyb3JNZXNzYWdlID0gbnVsbDsNCnRyeXsNCg0KCS8vIDEuIEdldCBhbiBh
bGdvcml0aG0gaW5zdGFuY2UuDQogICAgTWFjIHNoYTI1Nl9obWFjID0gTWFjLmdldEluc3RhbmNl
KGFsZ29yaXRobSk7DQoNCiAgICAvLyAyLiBDcmVhdGUgc2VjcmV0IGtleS4NCiAgICBTZWNyZXRL
ZXlTcGVjIHNlY3JldF9rZXkgPSBuZXcgU2VjcmV0S2V5U3BlYyhzZWNyZXRLZXkuZ2V0Qnl0ZXMo
IlVURi04IiksIGFsZ29yaXRobSk7DQoNCiAgICAvLyAzLiBBc3NpZ24gc2VjcmV0IGtleSBhbGdv
cml0aG0uDQogICAgc2hhMjU2X2htYWMuaW5pdChzZWNyZXRfa2V5KTsNCg0KICAgIC8vIDQuIEdl
bmVyYXRlIEJhc2U2NCBlbmNvZGVkIGNpcGhlciBzdHJpbmcuDQogICAvL2J5dGVbXSBoYXNoID0g
QmFzZTY0LmVuY29kZShzaGEyNTZfaG1hYy5kb0ZpbmFsKGlucHV0U3RyaW5nLmdldEJ5dGVzKCJV
VEYtOCIpKSk7DQogICAgDQogICBieXRlW10gaGFzaCA9IHNoYTI1Nl9obWFjLmRvRmluYWwoaW5w
dXRTdHJpbmcuZ2V0Qnl0ZXMoIlVURi04IikpOw0KICAgYnl0ZVtdIGhhc2hOZXc9ICBuZXcgYnl0
ZVsxNl07DQogICBpbnQgbGVuID0gaGFzaE5ldy5sZW5ndGg7DQogICANCiAgIGZvcihpbnQgaT0w
OyBpPGxlbjtpKyspew0KCSAgIGhhc2hOZXdbaV09aGFzaFtpXTsNCiAgIH0NCiAgIA0KICAgYnl0
ZSBbXSBlbmNvZGVIYXNoID0gIEJhc2U2NC5lbmNvZGUoaGFzaE5ldyk7DQogIA0KICAgDQogICBT
dHJpbmcgaGFzaFN0cmluZyA9IG5ldyBTdHJpbmcoZW5jb2RlSGFzaCk7DQogICANCiAgIGJ5dGVb
XSBoYXNoRmluYWwgPSBoYXNoU3RyaW5nLnJlcGxhY2VBbGwoIlxyXG4iLCIiKS5nZXRCeXRlcygp
Ow0KICAgDQogICBoYXNoVmFsdWUgPSBuZXcgU3RyaW5nKGhhc2hGaW5hbCk7DQoJDQp9Y2F0Y2gg
KEV4Y2VwdGlvbiBlKSB7IA0KCSBlcnJvck1lc3NhZ2UgPSBlLnRvU3RyaW5nKCk7DQp9DQoNCg0K
Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJoYXNoVmFsdWUiLCBo
YXNoVmFsdWUgKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJlcnJvck1lc3Nh
Z2UiLCBlcnJvck1lc3NhZ2UgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0KCQ0KCQ0K
</value>
</Values>
