<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getLastDayOfWeekForGivenDate</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required inDate</value>
    <value>[i] field:0:required inputFormat</value>
    <value>[i] field:0:required outputFormat</value>
    <value>[o] field:0:required outDate</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJaW5EYXRlID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJpbkRhdGUiICk7DQpTdHJpbmcJaW5wdXRGb3JtYXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBwaXBlbGluZUN1cnNvciwgImlucHV0Rm9ybWF0IiApOw0KU3RyaW5nCW91dHB1dEZvcm1hdCA9
IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAib3V0cHV0Rm9ybWF0IiApOw0K
cGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpTdHJpbmcgb3V0cHV0ID0gIiI7DQoNCnRyeQ0K
ew0KCWlmKGluRGF0ZSE9bnVsbCAmJiBpbkRhdGUhPSIiKQ0KCXsNCgkJU2ltcGxlRGF0ZUZvcm1h
dCBkYXRlRm9ybWF0ID0gbmV3IFNpbXBsZURhdGVGb3JtYXQoaW5wdXRGb3JtYXQpOw0KCQlEYXRl
IGNvbnZlcnRlZERhdGUgPSBkYXRlRm9ybWF0LnBhcnNlKGluRGF0ZSk7DQoJCUNhbGVuZGFyIGMg
PSBDYWxlbmRhci5nZXRJbnN0YW5jZSgpOw0KCQljLnNldFRpbWUoY29udmVydGVkRGF0ZSk7DQoN
CgkJYy5zZXQoQ2FsZW5kYXIuV0VFS19PRl9ZRUFSLCBJbnRlZ2VyLnBhcnNlSW50KGluRGF0ZS5z
dWJzdHJpbmcoaW5EYXRlLmxlbmd0aCgpLTIsIGluRGF0ZS5sZW5ndGgoKSkpKzIpOw0KCQljLnNl
dChDYWxlbmRhci5ZRUFSLCBJbnRlZ2VyLnBhcnNlSW50KGluRGF0ZS5zdWJzdHJpbmcoMCwgMikp
KTsNCgkJYy5zZXQoQ2FsZW5kYXIuREFZX09GX1dFRUssIENhbGVuZGFyLlNVTkRBWSk7DQoJCQ0K
CQlEYXRlIGRhdGVJblRpbWUgPSBjLmdldFRpbWUoKTsNCgkJU2ltcGxlRGF0ZUZvcm1hdCBzZGYg
PSBuZXcgU2ltcGxlRGF0ZUZvcm1hdChvdXRwdXRGb3JtYXQpOyANCgkJb3V0cHV0ID0gc2RmLmZv
cm1hdChkYXRlSW5UaW1lKTsNCgkNCgkJLy8gcGlwZWxpbmUNCgkJSURhdGFDdXJzb3IgcGlwZWxp
bmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KCQlJRGF0YVV0aWwucHV0KCBwaXBl
bGluZUN1cnNvcl8xLCAib3V0RGF0ZSIsIG91dHB1dCk7DQoJCXBpcGVsaW5lQ3Vyc29yXzEuZGVz
dHJveSgpOw0KCX0NCgllbHNlDQoJew0KCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiSW5w
dXQgZGF0ZSBpcyBlaXRoZXIgZW1wdHkgb3IgbnVsbCIpOw0KCX0NCn0NCmNhdGNoKEV4Y2VwdGlv
biBlKQ0Kew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsNCn0N
CgkNCg==</value>
</Values>
