<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">incrementDate</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required startingDate</value>
    <value>[i] field:0:required startingDateFormat</value>
    <value>[i] field:0:required endingDateFormat</value>
    <value>[i] field:0:optional addYears</value>
    <value>[i] field:0:optional addMonths</value>
    <value>[i] field:0:optional addDays</value>
    <value>[i] field:0:optional addHours</value>
    <value>[i] field:0:optional addMinutes</value>
    <value>[i] field:0:optional addSeconds</value>
    <value>[o] field:0:required endingDate</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCg0KU3RyaW5n
IHN0clN0YXJ0aW5nRGF0ZSA9IG51bGw7DQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoInN0YXJ0aW5n
RGF0ZSIpKQ0Kew0KICBzdHJTdGFydGluZ0RhdGUgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRW
YWx1ZSgpOw0KfQ0KZWxzZQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigic3RhcnRp
bmdEYXRlIG11c3QgYmUgc3VwcGxpZWQhIik7DQp9DQpTdHJpbmcgc3RyU3RhcnRpbmdEYXRlRm9y
bWF0ID0gbnVsbDsNCmlmIChpZGNQaXBlbGluZS5maXJzdCgic3RhcnRpbmdEYXRlRm9ybWF0Iikp
DQp7DQogIHN0clN0YXJ0aW5nRGF0ZUZvcm1hdCA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZh
bHVlKCk7DQp9DQplbHNlDQp7DQogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJzdGFydGlu
Z0RhdGVGb3JtYXQgbXVzdCBiZSBzdXBwbGllZCEiKTsNCn0NClN0cmluZyBzdHJFbmRpbmdEYXRl
Rm9ybWF0ID0gbnVsbDsNCmlmIChpZGNQaXBlbGluZS5maXJzdCgiZW5kaW5nRGF0ZUZvcm1hdCIp
KQ0Kew0KICBzdHJFbmRpbmdEYXRlRm9ybWF0ID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFs
dWUoKTsNCn0NCmVsc2UNCnsNCiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oImVuZGluZ0Rh
dGVGb3JtYXQgbXVzdCBiZSBzdXBwbGllZCEiKTsNCn0NCg0KU3RyaW5nIHN0ckFkZFllYXJzID0g
bnVsbDsNClN0cmluZyBzdHJBZGRNb250aHMgPSBudWxsOw0KU3RyaW5nIHN0ckFkZERheXMgPSBu
dWxsOw0KU3RyaW5nIHN0ckFkZEhvdXJzID0gbnVsbDsNClN0cmluZyBzdHJBZGRNaW51dGVzID0g
bnVsbDsNClN0cmluZyBzdHJBZGRTZWNvbmRzID0gbnVsbDsNCg0KaWYgKGlkY1BpcGVsaW5lLmZp
cnN0KCJhZGRZZWFycyIpKQ0Kew0KICBzdHJBZGRZZWFycyA9IChTdHJpbmcpIGlkY1BpcGVsaW5l
LmdldFZhbHVlKCk7DQp9DQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoImFkZE1vbnRocyIpKQ0Kew0K
ICBzdHJBZGRNb250aHMgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KfQ0KaWYg
KGlkY1BpcGVsaW5lLmZpcnN0KCJhZGREYXlzIikpDQp7DQogIHN0ckFkZERheXMgPSAoU3RyaW5n
KSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOw0KfQ0KaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJhZGRI
b3VycyIpKQ0Kew0KICBzdHJBZGRIb3VycyA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVl
KCk7DQp9DQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoImFkZE1pbnV0ZXMiKSkNCnsNCiAgc3RyQWRk
TWludXRlcyA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQp9DQppZiAoaWRjUGlw
ZWxpbmUuZmlyc3QoImFkZFNlY29uZHMiKSkNCnsNCiAgc3RyQWRkU2Vjb25kcyA9IChTdHJpbmcp
IGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7DQp9DQoNClNpbXBsZURhdGVGb3JtYXQgc3NkZiA9IG5l
dyBTaW1wbGVEYXRlRm9ybWF0KHN0clN0YXJ0aW5nRGF0ZUZvcm1hdCk7DQoNCkRhdGUgc3RhcnRp
bmdEYXRlID0gbnVsbDsNCnRyeQ0Kew0KICBzdGFydGluZ0RhdGUgPSBzc2RmLnBhcnNlKHN0clN0
YXJ0aW5nRGF0ZSk7DQp9DQpjYXRjaCAoRXhjZXB0aW9uIGUpDQp7DQogIHRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKGUudG9TdHJpbmcoKSk7DQp9DQoNCkdyZWdvcmlhbkNhbGVuZGFyIGdjID0g
bmV3IEdyZWdvcmlhbkNhbGVuZGFyKCk7DQpnYy5zZXRUaW1lKHN0YXJ0aW5nRGF0ZSk7DQoNCmlm
IChzdHJBZGRZZWFycyAhPSBudWxsKQ0Kew0KICBnYy5hZGQoQ2FsZW5kYXIuWUVBUiwgSW50ZWdl
ci5wYXJzZUludChzdHJBZGRZZWFycykpOw0KfQ0KaWYgKHN0ckFkZE1vbnRocyAhPSBudWxsKQ0K
ew0KICBnYy5hZGQoQ2FsZW5kYXIuTU9OVEgsIEludGVnZXIucGFyc2VJbnQoc3RyQWRkTW9udGhz
KSk7DQp9DQppZiAoc3RyQWRkRGF5cyAhPSBudWxsKQ0Kew0KICBnYy5hZGQoQ2FsZW5kYXIuREFZ
X09GX01PTlRILCBJbnRlZ2VyLnBhcnNlSW50KHN0ckFkZERheXMpKTsNCn0NCmlmIChzdHJBZGRI
b3VycyAhPSBudWxsKQ0Kew0KICBnYy5hZGQoQ2FsZW5kYXIuSE9VUl9PRl9EQVksIEludGVnZXIu
cGFyc2VJbnQoc3RyQWRkSG91cnMpKTsNCn0NCmlmIChzdHJBZGRNaW51dGVzICE9IG51bGwpDQp7
DQogIGdjLmFkZChDYWxlbmRhci5NSU5VVEUsIEludGVnZXIucGFyc2VJbnQoc3RyQWRkTWludXRl
cykpOw0KfQ0KaWYgKHN0ckFkZFNlY29uZHMgIT0gbnVsbCkNCnsNCiAgZ2MuYWRkKENhbGVuZGFy
LlNFQ09ORCwgSW50ZWdlci5wYXJzZUludChzdHJBZGRTZWNvbmRzKSk7DQp9DQoNCkRhdGUgZW5k
aW5nRGF0ZSA9IGdjLmdldFRpbWUoKTsNClNpbXBsZURhdGVGb3JtYXQgZXNkZiA9IG5ldyBTaW1w
bGVEYXRlRm9ybWF0KHN0ckVuZGluZ0RhdGVGb3JtYXQpOw0KU3RyaW5nIHN0ckVuZGluZ0RhdGUg
PSBlc2RmLmZvcm1hdChlbmRpbmdEYXRlKTsNCg0KaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImVu
ZGluZ0RhdGUiLCBzdHJFbmRpbmdEYXRlKTsNCmlkY1BpcGVsaW5lLmRlc3Ryb3koKTsNCgkNCg==
</value>
</Values>
